name: Github Action Demo
run-name: ${{github.actor}} is testing out Github Action
on: push
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{runner.os}} server hosted by Github!"
      - run: echo "The name of the branch is ${{github.ref}} and repository name is ${{github.repository}}."
      - name: Check out to repository code
        uses: actions/checkout@v3

      - run: echo "The ${{github.repository}} repository has been cleaned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner"
      - name: List files in the repository
        run: |
          ls ${{github.workspace}}
      - run: echo "The jobs's status is ${{jobs.status}}."
